version: "3.9"


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1


volumes:
  taw_mongo_data: {}


services:
  frontend:
    build:
      context: frontend
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.22.0.2
    restart: unless-stopped

  backend:
    build:
      context: backend
    networks:
      default:
        ipv4_address: 172.22.0.3
    restart: unless-stopped

  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    volumes:
      - taw_mongo_data:/data/db
    networks:
      default:
        ipv4_address: 172.22.0.4
    restart: unless-stopped
